title: Proton Control Animation
description: A Godot add-on for UI animation.
logo: "/img/icon.png"
favicon_ico: "/img/favicon.ico"
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

plugins:
  - jekyll-remote-theme

url: https://github.com/HungryProton/proton_control_animation

aux_links:
  Repository: https://github.com/HungryProton/proton_control_animation

navigation:
  - name: Overview
    link: /index.html
  - name: Installation
    link: /installation.html
  - name: Getting started
    link: /getting_started.html
  - name: Reference
    link: /reference/reference.html

hide_project_footer: true
