title: ProtonControlAnimation documentation
description: Documentation for the UI animation add-on.
logo: "icon.png"
favicon_ico: "icon.png"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

url: https://github.com/HungryProton/proton_control_animation

aux_links:
  Repository: https://github.com/HungryProton/proton_control_animation
